// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYY2oIdPSillt7SxUS438QzZbG0giGsk',
    appId: '1:351549247134:web:4b833ceefa98fd42d7358f',
    messagingSenderId: '351549247134',
    projectId: 'todo-app-48dbf',
    authDomain: 'todo-app-48dbf.firebaseapp.com',
    storageBucket: 'todo-app-48dbf.firebasestorage.app',
    measurementId: 'G-W57BLNLPNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk-y_mXCrFW6VyizAYM_QzEuGOuQX7qJs',
    appId: '1:351549247134:android:c89b903f09c986e2d7358f',
    messagingSenderId: '351549247134',
    projectId: 'todo-app-48dbf',
    storageBucket: 'todo-app-48dbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhF3aQGTk2BPOFVVzOVMA6TvyRrpvF-9s',
    appId: '1:351549247134:ios:5d330ccd623e9074d7358f',
    messagingSenderId: '351549247134',
    projectId: 'todo-app-48dbf',
    storageBucket: 'todo-app-48dbf.firebasestorage.app',
    iosClientId: '351549247134-a80a2c2d37ak14c1i93t14h16dd38adr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhF3aQGTk2BPOFVVzOVMA6TvyRrpvF-9s',
    appId: '1:351549247134:ios:5d330ccd623e9074d7358f',
    messagingSenderId: '351549247134',
    projectId: 'todo-app-48dbf',
    storageBucket: 'todo-app-48dbf.firebasestorage.app',
    iosClientId: '351549247134-a80a2c2d37ak14c1i93t14h16dd38adr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYY2oIdPSillt7SxUS438QzZbG0giGsk',
    appId: '1:351549247134:web:aeeae0f334f20cc3d7358f',
    messagingSenderId: '351549247134',
    projectId: 'todo-app-48dbf',
    authDomain: 'todo-app-48dbf.firebaseapp.com',
    storageBucket: 'todo-app-48dbf.firebasestorage.app',
    measurementId: 'G-DL6YR39164',
  );

}